version: "3"
services:
    db:
        container_name: "mysql"
        image: mysql:5.7
        volumes:
          - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          
    www:
        container_name: "apache"
        depends_on:
            - db
        build: .
        ports:
            - "80:80"
        volumes:
            - ./laravel6:/var/www/html/
        networks:
            - default
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: test
    phpmyadmin-laravel6:
        container_name: phpmyadmin-laravel6
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - PMA_USER=root
          - PMA_PASSWORD=password
        ports:
          - "8080:80"
        links:
          - db:db
        depends_on:
          - db
    
volumes:
    db_data: {}